#!/bin/bash

help () {
	curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help/main.txt
	return
}

if [[ $# -lt 1 ]] ; then
	help
	exit 0
elif [[ $# -eq 1 && $1 -eq "help" ]] ; then
	help
	exit 0
elif [[ $# -eq 2 && $1 -eq "help" ]] ; then
	case $2 in
		"compost")
			curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help/compost.txt
			;;
		*)
			printf "Invalid option" && exit 0
			;;
	esac
fi