#!/bin/bash

help () {
	printf $(curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help.txt)
	# cat help.txt
	return
}

if [[ $# -lt 1 ]] ; then
	help
	exit 0
elif [[ $# -eq 1 && $1 -eq "help" ]] ; then
	help
	exit 0
fi